name: konami

networks:
  default:
    driver: bridge

services:
  couchdb:
    image: couchdb:2.3
    hostname: db.kz

  amqp:
    image: rabbitmq
    hostname: amqp.kz

  kz:
    image: kz
    hostname: kz.kz
    build:
      context: ./kazoo
      cache_from:
        - centos:7
    volumes:
      - ./kazoo/config.ini:/etc/kazoo/core/config.ini
      - ./kazoo/sys.config:/etc/kazoo/core/sys.config

  kama:
    image: kama
    hostname: kama.kz
    build:
      context: ./kamailio
      cache_from:
        - centos:7
    environment:
      AMQP_URL: amqp://guest:guest@amqp.kz:5672
    volumes:
      - ./kamailio/local.cfg:/etc/kazoo/kamailio/local.cfg
      - ./kamailio/kazoo-kamailio:/sbin/kazoo-kamailio
