name: konami

include:
  - ./docker/networks.yaml
  - ./docker/services/syslog.yaml
  - ./docker/services/couchdb.yaml
  - ./docker/services/amqp.yaml
  - ./docker/services/kama.yaml
  - ./docker/services/kz.yaml
  - ./docker/services/fs-kz.yaml
  - ./docker/services/fs-devices.yaml
