name: konami

include:
  - ./compose/networks.yaml
  - ./compose/services/couchdb.yaml
  - ./compose/services/amqp.yaml
  - ./compose/services/kama.yaml
  - ./compose/services/kz.yaml
  - ./compose/services/fs-kz.yaml
  - ./compose/services/fs-devices.yaml
  - ./compose/services/fs-pstn.yaml
