services:
  grafana:
    image: grafana/grafana-oss
    hostname: grafana.kz
    volumes:
      - ${ROOT_DIR}/etc/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ${ROOT_DIR}/etc/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ${ROOT_DIR}/etc/grafana/dashboards:/dashboards
    extends:
      file: ${ROOT_DIR}/src/logging.yaml
      service: logging
