services:
  kama:
    image: ${PREFIX}kamailio
    hostname: kama.kz
    environment:
      AMQP_URL: amqp://guest:guest@amqp.kz:5672
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://172.17.18.4"
        tag: kamailio
