services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus.kz
    volumes:
      - ${ROOT_DIR}/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extends:
      file: ${ROOT_DIR}/src/logging.yaml
      service: logging
