services:
  syslog:
    user: ${UID}:${GID}
    build:
      context: ${ROOT_DIR}/src/images
      dockerfile_inline: |
        from rsyslog/syslog_appliance_alpine
        run chown -R ${UID}:${GID} /config
    hostname: syslog.kz
    volumes:
      - ${ROOT_DIR}/log:/log
      - ${ROOT_DIR}/etc/syslog/rsyslog.conf:/etc/rsyslog.conf
    networks:
      default:
        ipv4_address: 172.17.18.4
