services:
  fs-kz:
    image: ${PREFIX}freeswitch
    hostname: fs-kz.kz
    pre_stop:
      - command: fs_cli -x shutdown
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://172.17.18.4"
        tag: freeswitch
