services:
  kama:
    image: ${PREFIX}kamailio
    hostname: kama.kz
    environment:
      AMQP_URL: amqp://guest:guest@amqp.kz:5672
    volumes:
      - ./kamailio/local.cfg:/etc/kazoo/kamailio/local.cfg
      - ./kamailio/kazoo-kamailio:/sbin/kazoo-kamailio
