services:
  kz:
    image: ${PREFIX}kazoo
    hostname: kz.kz
    networks:
      default:
        ipv4_address: 172.17.18.3
    post_start:
      - command: init.sh
    pre_stop:
      - command: sup init stop
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://172.17.18.4"
        tag: kazoo
