services:
  kz:
    image: ${PREFIX}kazoo
    hostname: kz.kz
    volumes:
      - ./kazoo/config.ini:/etc/kazoo/core/config.ini
      - ./kazoo/sys.config:/etc/kazoo/core/sys.config
      - ./kazoo/init.sh:/usr/local/bin/init.sh
