services:
  role-freeswitch:
    image: ${PROJECT}-freeswitch
    pre_stop:
      - command: fs_cli -x shutdown
    extends:
      file: ${ROOT_DIR}/src/logging.yaml
      service: logging
    logging:
      options:
        tag: freeswitch
