services:
  role-kamailio:
    image: ${PREFIX}kamailio
    environment:
      AMQP_URL: amqp://guest:guest@amqp.kz:5672
    extends:
      file: ${ROOT_DIR}/src/logging.yaml
      service: logging
    logging:
      options:
        tag: kamailio
