services:
  role-kazoo-apps:
    image: ${PROJECT}-kazoo
    pre_stop:
      - command: sup init stop
    extends:
      file: ${ROOT_DIR}/src/logging.yaml
      service: logging
    logging:
      options:
        tag: kazoo
