services:
  role-kazoo-apps:
    extends:
      file: ${ROOT_DIR}/src/roles/kazoo-apps-base.yaml
      service: role-kazoo-apps-base
    image: ${PROJECT}-kazoo
    volumes:
      - ${ROOT_DIR}/etc/kazoo/config.ini:/etc/kazoo/core/config.ini
      - ${ROOT_DIR}/etc/kazoo/sys.config:/etc/kazoo/core/sys.config
