services:
  fs-devices:
    image: ${PREFIX}freeswitch
    hostname: fs-devices.kz
    volumes:
      - ${ROOT_DIR}/etc/freeswitch/devices/:/etc/kazoo/freeswitch/
      - ${ROOT_DIR}/docker/services/fs-devices/bin/:/usr/local/bin/
    post_start:
      - command: wait-for-regs.sh
    pre_stop:
      - command: fs_cli -x shutdown
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://172.17.18.4"
        tag: devices
